In [ ]:
#Задание №1

In [1]:
import numpy as np

In [36]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [4]:
a

[[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]]

In [38]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

In [20]:
#Задание №2

In [41]:
a_centered = a - mean_a
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [ ]:
#Задание №3

In [44]:
a1 = a_centered[: , 0]
a2 = a_centered[: , 1]
a_centered_sp = np.dot(a1, a2)
a_centered_sp

8.0

In [45]:
N = a.shape[0]
N

5

In [49]:
sqr = a_centered_sp/(N-1)
sqr

2.0

In [ ]:
#Задание №4

In [52]:
np.cov(a.transpose())

array([[1. , 2. ],
       [2. , 4.3]])

In [54]:
np.save("home1npy.npy", a)